apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  # creationTimestamp: null
  labels:
    io.kompose.service: test-rpx
  name: test-rpx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: test-rpx
  strategy: {}
  template:
    metadata:
      # creationTimestamp: null
      labels:
        io.kompose.service: test-rpx
    spec:
      containers:
      - name: test-rpx
        env:
          - name: env
            value: "env smaple"                             
        image: kmpartner/test-rpx
        ports:
        - containerPort: 443
        # - containerPort: 80

        # readinessProbe:
        #   tcpSocket:
        #     port: 8443
        #   initialDelaySeconds: 10
        #   periodSeconds: 60
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8501
        #   initialDelaySeconds: 60
        #   failureThreshold: 3
        #   periodSeconds: 60
        # startupProbe:
        #   httpGet:
        #     path: /
        #     port: 8443
        #   failureThreshold: 60
        #   periodSeconds: 10
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
  
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}