web:
  image: nginx-env-test2
  volumes:
   - ./nginx.conf.templates:/etc/nginx/templates
  ports:
   - "8085:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
   - MESSAGE="Hello World!!!"