apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-first-8080
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: hello-kubernetes-first-8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-first-8080
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes-first-8080
  template:
    metadata:
      labels:
        app: hello-kubernetes-first-8080
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello from the first deployment!