apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  # creationTimestamp: null
  labels:
    io.kompose.service: ngi-env-ws-rpx
  name: ngi-env-ws-rpx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ngi-env-ws-rpx
  strategy: {}
  template:
    metadata:
      # creationTimestamp: null
      labels:
        io.kompose.service: ngi-env-ws-rpx
    spec:
      containers:
      - name: ngi-env-ws-rpx
        env:
          - name: env
            value: "env smaple"
          - name: API_HOST
            value: "hello-kubernetes-first-8080:8080"
          - name: MAX_BODY_SIZE
            value: "1M"
          - name: DOLLAR
            value: "$"
          - name: HOST
            value: "$host"
          - name: X_REAL_IP
            value: "$remote_addr"
          - name: X_FORWARDED_FOR
            value: "$proxy_add_x_forwarded_for"
          - name: X_FORWARDED_PROTO
            value: "$scheme"

        # image: kmpartner/ngi-env-ws-rpx:1.17.8-alpine
        # image: kmpartner/ngi-env-ws-rpx:1.17.8-alpine-2
        image: kmpartner/ngi-env-ws-rpx:1.17.8-alpine-3
        ports:
        - containerPort: 443
        # - containerPort: 80

        # readinessProbe:
        #   tcpSocket:
        #     port: 8443
        #   initialDelaySeconds: 10
        #   periodSeconds: 60
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8501
        #   initialDelaySeconds: 60
        #   failureThreshold: 3
        #   periodSeconds: 60
        # startupProbe:
        #   httpGet:
        #     path: /
        #     port: 8443
        #   failureThreshold: 60
        #   periodSeconds: 10
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"

        imagePullPolicy: Always
  
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}